#
# Copyright (C) 2025-2026, AdaCore
#

[tox]
envlist = py312
skipsdist = True

[testenv]
description = Build and install both support/* packages as wheels, then run pytest.
deps =
    pytest
    {toxinidir}/support/rts_prebuilder_project
    {toxinidir}/support/bb_runtimes_targets_gen
commands =
    pytest {toxinidir}/tests/packaging {posargs}
