	.section .rodata,"a"
// First level: 1 (w/ 2 entries), max VA: 2**31
	.p2align 12
__mmu_part1_l2_000040000:
	.dword 0x00000000020006fd  // for 0x40000000, RAM
	.dword 0x00000000022006fd  // for 0x40200000, RAM
	.dword 0x00000000024006fd  // for 0x40400000, RAM
	.dword 0x00000000026006fd  // for 0x40600000, RAM
	.dword 0x00000000028006fd  // for 0x40800000, RAM
	.dword 0x0000000002a006fd  // for 0x40a00000, RAM
	.dword 0x0000000002c006fd  // for 0x40c00000, RAM
	.dword 0x0000000002e006fd  // for 0x40e00000, RAM
	.dword 0x00000000030006fd  // for 0x41000000, RAM
	.dword 0x00000000032006fd  // for 0x41200000, RAM
	.dword 0x00000000034006fd  // for 0x41400000, RAM
	.dword 0x00000000036006fd  // for 0x41600000, RAM
	.dword 0x00000000038006fd  // for 0x41800000, RAM
	.dword 0x0000000003a006fd  // for 0x41a00000, RAM
	.dword 0x0000000003c006fd  // for 0x41c00000, RAM
	.dword 0x0000000003e006fd  // for 0x41e00000, RAM
	.dword 0x00000000040006fd  // for 0x42000000, RAM
	.dword 0x00000000042006fd  // for 0x42200000, RAM
	.dword 0x00000000044006fd  // for 0x42400000, RAM
	.dword 0x00000000046006fd  // for 0x42600000, RAM
	.dword 0x00000000048006fd  // for 0x42800000, RAM
	.dword 0x0000000004a006fd  // for 0x42a00000, RAM
	.dword 0x0000000004c006fd  // for 0x42c00000, RAM
	.dword 0x0000000004e006fd  // for 0x42e00000, RAM
	.dword 0x00000000050006fd  // for 0x43000000, RAM
	.dword 0x00000000052006fd  // for 0x43200000, RAM
	.dword 0x00000000054006fd  // for 0x43400000, RAM
	.dword 0x00000000056006fd  // for 0x43600000, RAM
	.dword 0x00000000058006fd  // for 0x43800000, RAM
	.dword 0x0000000005a006fd  // for 0x43a00000, RAM
	.dword 0x0000000005c006fd  // for 0x43c00000, RAM
	.dword 0x0000000005e006fd  // for 0x43e00000, RAM
	.dword 0x00000000060006fd  // for 0x44000000, RAM
	.dword 0x00000000062006fd  // for 0x44200000, RAM
	.dword 0x00000000064006fd  // for 0x44400000, RAM
	.dword 0x00000000066006fd  // for 0x44600000, RAM
	.dword 0x00000000068006fd  // for 0x44800000, RAM
	.dword 0x0000000006a006fd  // for 0x44a00000, RAM
	.dword 0x0000000006c006fd  // for 0x44c00000, RAM
	.dword 0x0000000006e006fd  // for 0x44e00000, RAM
	.dword 0x00000000070006fd  // for 0x45000000, RAM
	.dword 0x00000000072006fd  // for 0x45200000, RAM
	.dword 0x00000000074006fd  // for 0x45400000, RAM
	.dword 0x00000000076006fd  // for 0x45600000, RAM
	.dword 0x00000000078006fd  // for 0x45800000, RAM
	.dword 0x0000000007a006fd  // for 0x45a00000, RAM
	.dword 0x0000000007c006fd  // for 0x45c00000, RAM
	.dword 0x0000000007e006fd  // for 0x45e00000, RAM
	.dword 0x00000000080006fd  // for 0x46000000, RAM
	.dword 0x00000000082006fd  // for 0x46200000, RAM
	.dword 0x00000000084006fd  // for 0x46400000, RAM
	.dword 0x00000000086006fd  // for 0x46600000, RAM
	.dword 0x00000000088006fd  // for 0x46800000, RAM
	.dword 0x0000000008a006fd  // for 0x46a00000, RAM
	.dword 0x0000000008c006fd  // for 0x46c00000, RAM
	.dword 0x0000000008e006fd  // for 0x46e00000, RAM
	.dword 0x00000000090006fd  // for 0x47000000, RAM
	.dword 0x00000000092006fd  // for 0x47200000, RAM
	.dword 0x00000000094006fd  // for 0x47400000, RAM
	.dword 0x00000000096006fd  // for 0x47600000, RAM
	.dword 0x00000000098006fd  // for 0x47800000, RAM
	.dword 0x0000000009a006fd  // for 0x47a00000, RAM
	.dword 0x0000000009c006fd  // for 0x47c00000, RAM
	.dword 0x0000000009e006fd  // for 0x47e00000, RAM
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.dword 0
	.p2align 12
__mmu_part1_l1_000040000:
	.dword 0
	.dword __mmu_part1_l2_000040000 + 0x3
	.type __memmap_part1, @object
__memmap_part1:
	.dword 0x40000000
	.dword 0x2000000
	.dword 0x8000000
	.size __memmap_part1, . - __memmap_part1
	.type __files_part1_name_0, @object
__files_part1_name_0:
	.asciz "dtb"
	.size __files_part1_name_0, . - __files_part1_name_0
	.type __files_part1_content_0, @object
__files_part1_content_0:
	.incbin "../linux/mc.dtb"
__files_part1_content_0_end:
	.size __files_part1_content_0, . - __files_part1_content_0
	.type __files_part1_name_1, @object
__files_part1_name_1:
	.asciz "linux"
	.size __files_part1_name_1, . - __files_part1_name_1
	.type __files_part1_content_1, @object
__files_part1_content_1:
	.incbin "../linux/Image"
__files_part1_content_1_end:
	.size __files_part1_content_1, . - __files_part1_content_1
	.type __files_part1_name_2, @object
__files_part1_name_2:
	.asciz "initrd"
	.size __files_part1_name_2, . - __files_part1_name_2
	.type __files_part1_content_2, @object
__files_part1_content_2:
	.incbin "../linux/initramfs.cpio.gz"
__files_part1_content_2_end:
	.size __files_part1_content_2, . - __files_part1_content_2

	.type __files_part1, @object
__files_part1:
	.dword __files_part1_name_0
	.dword __files_part1_content_0
	.dword __files_part1_content_0_end - __files_part1_content_0
	.dword __files_part1_name_1
	.dword __files_part1_content_1
	.dword __files_part1_content_1_end - __files_part1_content_1
	.dword __files_part1_name_2
	.dword __files_part1_content_2
	.dword __files_part1_content_2_end - __files_part1_content_2
	.size __files_part1, . - __files_part1

	.globl __dir_part1
	.type __dir_part1, @object
__dir_part1:
	.dword __mmu_part1_l1_000040000
	.dword __memmap_part1
	.word 1
	.word 0
	.dword __files_part1
	.word 3
	.word 0
	.size __dir_part1, . - __dir_part1

